# Generated by Django 4.0.5 on 2022-07-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
